### ISSUE TITLE
Roadmap v1

### ISSUE THREAD

**Issue by nverinaud** [Ryfacto/ryfacto.fr#4]
Voilà une petite checklist pour une v1 "idéale".

Par ordre d'importance:
- [x] Nos valeurs
- [x] Contact
- [x] Google Analytics
- [x] Mentions légales
- [x] SEO `<meta description>`
- [x] Nos services
- [x] Social Proof / Nos clients
- [ ] Notre méthodologie de travail
- [ ] Nos réalisations (+ page de détail)
- [ ] L'équipe
- [ ] Technologies
- [ ] Nous retrouver (BBL, meetups, etc)
- [ ] Ils nous inspirent (citations Beck, Martin, Fowler, etc)
- [ ] Dernières actu (ajax fil twitter / medium ?)
